import appinspectEvents from "../../../../demo/appinspect_events.json";
import appinspectProvenanceRaw from "../../../../demo/appinspect_provenance.jsonl?raw";
import onboardingEvents from "../../../../demo/onboarding_events.json";
import onboardingProvenanceRaw from "../../../../demo/onboarding_provenance.jsonl?raw";

import { parseProvenance } from "../lib/replay";
import type { LoopName, ProvenanceEntry, ReplayEvent } from "../types";

export interface StageArtifact {
  type: string;
  path: string;
  status: string;
}

export interface StageDataset {
  loop: LoopName;
  index: number;
  label: string;
  tagline: string;
  artifactsLabel: string;
  events: ReplayEvent[];
  provenance: ProvenanceEntry[];
  artifacts: StageArtifact[];
}

export const STAGES: Record<LoopName, StageDataset> = {
  appinspect: {
    loop: "appinspect",
    index: 2,
    label: "AppInspect",
    tagline: "AppInspect self-heal replay",
    artifactsLabel: "Generated by AppInspect loop",
    events: appinspectEvents as ReplayEvent[],
    provenance: parseProvenance(appinspectProvenanceRaw),
    artifacts: [
      { type: "Initial Report", path: "appinspect/iteration-00.json", status: "failed" },
      { type: "Validation Report", path: "appinspect/iteration-01.json", status: "patched" },
      { type: "Validation Report", path: "appinspect/iteration-02.json", status: "patched" },
      { type: "Final Report", path: "appinspect/iteration-03.json", status: "clean" },
      { type: "Replay Events", path: "events.json", status: "replay" },
      { type: "Provenance", path: "provenance.jsonl", status: "ledger" }
    ]
  },
  onboarding: {
    loop: "onboarding",
    index: 1,
    label: "Onboarding",
    tagline: "Live MCP onboarding self-heal replay",
    artifactsLabel: "Generated by onboarding loop",
    events: onboardingEvents as ReplayEvent[],
    provenance: parseProvenance(onboardingProvenanceRaw),
    artifacts: [
      { type: "Naive Candidate", path: "onboarding/candidate-00.spl", status: "failed" },
      { type: "Robust Candidate", path: "onboarding/candidate-01.spl", status: "clean" },
      { type: "Validation Report", path: "onboarding/validation-00.json", status: "failed" },
      { type: "Validation Report", path: "onboarding/validation-01.json", status: "clean" },
      { type: "Replay Events", path: "events.json", status: "replay" },
      { type: "Provenance", path: "provenance.jsonl", status: "ledger" }
    ]
  }
};

export const STAGE_ORDER: LoopName[] = ["onboarding", "appinspect"];
export const DEFAULT_STAGE: LoopName = "appinspect";
